---
title: "220126 Vectorized arithmetic"
author: "Mark Allan Co Jacob"
date: "1/26/2022"
output: html_document
---

```{r}

c(1,2,3,4)
1:4
4:1
-1:2 # note precendence
seq(1,4)
seq(2,8, by=2)
seq(0,1,length=11)
c(1,2,3,4)/2
c(1,2,3,4)/c(4,3,2,1)
1/c(1,2,3,4)
log(c(0.1,1,10,100),10) #Nested Function with c(0.1,1,10,100) is logged with base 10
c(1,2,3,4) + c(4,3) # This is recycling; each number in c is added in alternating order of 4 and 3.
c(1,2,3,4) + c(4,3,2) # each number is added in sequence by the second vector.

x <- c(1,3.5,-28.4,10)
x
sum(x)
prod(x)
mean(x)

x <- c(1,5,10,NA,15) #NA is a recognized symbol in R that indicates there should be a value here, but it isn't. 
x
sum(x) # na.rm is an NA checker, stops the function from operating if an NA is within a vector.
sum(x,na.rm=FALSE)
prod(x, na.rm=FALSE)
mean(x,na.rm=FALSE)
sum(x,na.rm=TRUE) # na.rm = TRUE ignores NA values and proceeds with the calculation.
prod(x, na.rm=TRUE)
mean(x,na.rm=TRUE)








```

### More on creating simple vectors

```{r}

rep(2,10) # Repeats 2 five times
rep(c(1,2,3),5) # repeats 1, 2, and 3 five times
rep(c(1,2,3),c(2,4,5)) #repeats 1 two times, 2 four times, and 3 five times.

rep(1:3,4) #repeats numbers 1 through 3 four times.

rep(1:3,rep(4,3)) #repeats numbers 1 through 3 four times then does it in three instances.

x <- c(1,3.5,-28.4,10)

x <- c("cat","dog","mouse","monkey") #Turned into a character when stored

x <- c(TRUE,TRUE,TRUE,FALSE,FALSE)
x = c(TRUE,TRUE,TRUE,FALSE,FALSE) # Using = or <- is the same but use <- since it is less sloppy. = is also used in other scenarios.

1:10
3:8
-3:8
8:2
10:10
5.2:20 #Using this directly lists numbers in increments of 1 to the number 20.

seq(1,10, 1)
seq(3,9,by=3)

log(seq(1,2,length=11)) #Logs the eleven numbers between 1 and 2.

log10(seq(1,100,length = 11))

log2(c(1,2,4,8,16,32))








```

### End Session


```{r}

x <- c(0.008, 0.018, 0.056, 0.055, 0.135,
       0.052, 0.077, 0.026, 0.044, 0.300,
       0.025, 0.036, 0.043, 0.100, 0.120,
       0.110, 0.100, 0.350, 0.100, 0.300,
       0.011, 0.060, 0.070, 0.050, 0.080,
       0.110, 0.110, 0.120, 0.133, 0.100,
       0.100, 0.155, 0.370, 0.019, 0.100,
       0.100, 0.116)
x
length(X)
str(x)
class(x)

plot(x) # plots each value as y in a scatterplot and defaults the values in order as it appears in the vector.

mean(x)
median(x)
max(x)
range(x)
summary(x)
quantile(x)

quantile(x,probs=c(0.25,0.75))
diff(quantile(x,probs=c(0.25,0.75)))
IQR(x)
sd(x)
mad(x) #Median Absolute Deviation - Equivalent to SD, but more robust and less sensitive to outliers. Use this rather than standard deviation.

```

###Visualizing Data

```{r}

#histograms with different numbers of bins
hist(x)
hist(x,breaks=5) #less bins and fits between 5 x-axis ticks
hist(x,breaks=15) #more bins and fits data between 15 x-axis ticks

#plots values by index
plot(x)
plot(x,type="l") #Time series worthy
plot(x,type="b") # Values connected by lines

#Dot plots
stripchart(x) #y axis has no meaning, 1-dimensional
set.seed(1)
stripchart(x,method="jitter") #Jitter moves the points up and down randomly instead of having it in one dimension
stripchart(x,vertical=TRUE,method="jitter",pch=1) #pch changes the shape of the data points

abline(h=1,lty=2,col="gray70") #Lower level plot function that needs to be ran with a plotting function. It adds onto the created plot. Lots of features with abline function.



```


